# SITE CONFIGURATION
title: Gary Thornton # your site title
author: Gary Thornton # You :P
description: > # Meta description of Homepage
  Gary Thornton, User Experience Architect, Portfolio and CV.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://garythornton.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Gary Thornton
  links:
#/garythornton/portfolio   https://pages.github.ibm.com  
#- https://twitter.com/BenBalter
#    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/tempgary-thornton-3401a53
#    - https://plus.google.com/+BenBalter
    - https://github.com/tempgarythornton
#    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Portfolio', link: '/8f180f4d437888a0397dd692eb3b098b7361d146'}
  - {name: 'Profile', link: '/about'}
#  - {name: 'Contact', link: '/contact'}

tagline: >
  User Experience Design
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: gary_thornton@hotmail.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  garythornton # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
